#Cross Validation Evaluating Model Performance

# Option 1 : Use all available data for training and test on same dataset
#ex 100 math questions ,few questions from same 100 math questions that was trained 
# option 2 : Split available dataset into training and test--> sets train 70 test 30
#ex 100 math questions ,few questions from same 70 math questions that was trained 30 questions to test
# Option 3 K fold Cross Validation
#100 samples --> 5 folds --> 20 samples each --> 1 for test 2 to 5 train a model (Note score)--> 2 for test 1,3 to 5 train a model --> So on...
At final avg all scores

In [9]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
digits = load_digits()

In [23]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(digits.data,digits.target,test_size=0.3)

In [24]:
lr = LogisticRegression() # It is ML model which is trying to classify your samples
lr.fit(X_train,y_train)
lr.score(X_test,y_test)

C:\Users\Chandra Mouli\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

0.9666666666666667

In [25]:
svm = SVC()
svm.fit(X_train,y_train)
svm.score(X_test,y_test)

0.9888888888888889

In [27]:
rf = RandomForestClassifier(n_estimators = 40)
rf.fit(X_train,y_train)
rf.score(X_test,y_test) # Run Multiple times to see score which model is changing

0.9685185185185186

In [29]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [30]:
for train_index,test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]

In [31]:
def get_score(model,X_train,X_test,y_train,y_test):
    model.fit(X_train,y_train)
    return model.score(X_test,y_test)

In [32]:
get_score(LogisticRegression(),X_train,X_test,y_train,y_test)

C:\Users\Chandra Mouli\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

0.9666666666666667

In [33]:
get_score(SVC(),X_train,X_test,y_train,y_test)

0.9888888888888889

In [35]:
get_score(RandomForestClassifier(),X_train,X_test,y_train,y_test)

0.975925925925926

In [37]:
from sklearn.model_selection import StratifiedKFold
 # similiar to KFold it is little better when you are seprating out folds it will divide folds catergorically uniformly
folds = StratifiedKFold(n_splits = 3)

In [48]:
scores_l = []
scores_svm = []
scores_rf = []
for train_index,test_index in kf.split(digits.data):
    X_train,X_test,y_train,y_test = digits.data[train_index],digits.data[test_index],\
                                    digits.target[train_index],digits.target[test_index]
    scores_l.append(get_score(LogisticRegression(max_iter=1000),X_train,X_test,y_train,y_test))
    scores_svm.append(get_score(SVC(),X_train,X_test,y_train,y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators = 40),X_train,X_test,y_train,y_test))

In [49]:
scores_l,scores_svm,scores_rf

([0.9248747913188647, 0.9432387312186978, 0.9148580968280468],
 [0.9666110183639399, 0.9816360601001669, 0.9549248747913188],
 [0.9315525876460768, 0.9499165275459098, 0.9348914858096828])

In [50]:
from sklearn.model_selection import cross_val_score

In [52]:
cross_val_score(LogisticRegression(max_iter=1000),digits.data,digits.target)

array([0.92222222, 0.86944444, 0.94150418, 0.94150418, 0.89693593])

In [53]:
cross_val_score(SVC(),digits.data,digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [55]:
cross_val_score(RandomForestClassifier(n_estimators=40),digits.data,digits.target)

array([0.93055556, 0.87777778, 0.95821727, 0.95543175, 0.92479109])

In [56]:
cross_val_score(RandomForestClassifier(n_estimators=5),digits.data,digits.target)

array([0.82222222, 0.80833333, 0.88857939, 0.89415042, 0.80501393])

In [57]:
cross_val_score(RandomForestClassifier(n_estimators=15),digits.data,digits.target)

array([0.92222222, 0.85833333, 0.95543175, 0.94986072, 0.90250696])

In [60]:
cross_val_score(RandomForestClassifier(n_estimators=50),digits.data,digits.target)

array([0.92777778, 0.90555556, 0.95821727, 0.94986072, 0.91364903])

In [65]:
from sklearn.datasets import load_iris
import pandas as pd
iris = load_iris()

In [66]:
dir(iris)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [68]:
df = pd.DataFrame(iris.data,columns = iris.feature_names)
df.head()

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [70]:
df['target'] = iris.target
df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0

In [71]:
cross_val_score(RandomForestClassifier(n_estimators=50),df.drop(['target'],axis = 'columns'),iris.target)

array([0.96666667, 0.96666667, 0.93333333, 0.9       , 1.        ])

In [72]:
cross_val_score(SVC(),df.drop(['target'],axis = 'columns'),iris.target)

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [73]:
cross_val_score(LogisticRegression(max_iter=100),df.drop(['target'],axis = 'columns'),iris.target)

C:\Users\Chandra Mouli\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [75]:
from sklearn.tree import DecisionTreeClassifier
d_scores = cross_val_score(DecisionTreeClassifier(), iris.data, iris.target)
d_scores

array([0.96666667, 0.96666667, 0.9       , 0.96666667, 1.        ])