In [1]:
import pandas as pd

In [2]:
india_weather = pd.DataFrame({
'city' : ['mumbai','delhi','banglore'],
'temperature':[32,45,30],
'humidity':[80,60,78]
})
india_weather

       city  temperature  humidity
0    mumbai           32        80
1     delhi           45        60
2  banglore           30        78

In [3]:
us_weather = pd.DataFrame({
'city' : ['new york','chicago','dallas'],
'temperature':[21,14,35],
'humidity':[68,65,75]
})
us_weather

       city  temperature  humidity
0  new york           21        68
1   chicago           14        65
2    dallas           35        75

In [4]:
df = pd.concat([india_weather,us_weather])
df

       city  temperature  humidity
0    mumbai           32        80
1     delhi           45        60
2  banglore           30        78
0  new york           21        68
1   chicago           14        65
2    dallas           35        75

In [5]:
df = pd.concat([india_weather,us_weather],ignore_index = True)
df

       city  temperature  humidity
0    mumbai           32        80
1     delhi           45        60
2  banglore           30        78
3  new york           21        68
4   chicago           14        65
5    dallas           35        75

In [6]:
df = pd.concat([india_weather,us_weather],keys = ["india","us"])
df

             city  temperature  humidity
india 0    mumbai           32        80
      1     delhi           45        60
      2  banglore           30        78
us    0  new york           21        68
      1   chicago           14        65
      2    dallas           35        75

In [8]:
df.loc["us"] # if u use keys like this it is helpful

       city  temperature  humidity
0  new york           21        68
1   chicago           14        65
2    dallas           35        75

In [12]:
temperature_df = pd.DataFrame({
'city':['mumbai','delhi','banglore'],
'temperature':[32,45,30]
},index=[0,1,2])
temperature_df

       city  temperature
0    mumbai           32
1     delhi           45
2  banglore           30

In [13]:
windspeed_df = pd.DataFrame({
'city':['delhi','mumbai'],
'windspeed':[7,12]
},index=[1,0])
windspeed_df

     city  windspeed
1   delhi          7
0  mumbai         12

In [14]:
pd.concat([temperature_df,windspeed_df],axis=1)

       city  temperature    city  windspeed
0    mumbai           32  mumbai       12.0
1     delhi           45   delhi        7.0
2  banglore           30     NaN        NaN

In [15]:
#merge
df1 = pd.DataFrame({
'city' : ['new york','chicago','dallas'],
'temperature':[21,14,35],
})
df1

       city  temperature
0  new york           21
1   chicago           14
2    dallas           35

In [16]:
df2 = pd.DataFrame({
'city' : ['new york','chicago','dallas'],
'humidity':[68,65,75]})
df2

       city  humidity
0  new york        68
1   chicago        65
2    dallas        75

In [17]:
df3 = pd.merge(df1,df2, on = 'city')
df3

       city  temperature  humidity
0  new york           21        68
1   chicago           14        65
2    dallas           35        75

In [19]:
df4 = pd.DataFrame({
'city' : ['new york','chicago','dallas','baltimore'],
'temp':[68,65,75,56]})
df4

        city  temp
0   new york    68
1    chicago    65
2     dallas    75
3  baltimore    56

In [29]:
df5 = pd.DataFrame({
'city' : ['new york','chicago','orlando','san fransico'],
'humidity':[68,65,75,45]})
df5

           city  humidity
0      new york        68
1       chicago        65
2       orlando        75
3  san fransico        45

In [30]:
df6 = pd.merge(df4,df5,on='city')
df6   #because it is given common in 2 df so by default it is inner join

       city  temp  humidity
0  new york    68        68
1   chicago    65        65

In [31]:
df6 = pd.merge(df4,df5,on='city',how='left')
df6

        city  temp  humidity
0   new york    68      68.0
1    chicago    65      65.0
2     dallas    75       NaN
3  baltimore    56       NaN

In [32]:
df6 = pd.merge(df4,df5,on='city',how='right')
df6

           city  temp  humidity
0      new york  68.0        68
1       chicago  65.0        65
2       orlando   NaN        75
3  san fransico   NaN        45

In [33]:
df6 = pd.merge(df4,df5,on='city',how='outer')
df6

           city  temp  humidity
0     baltimore  56.0       NaN
1       chicago  65.0      65.0
2        dallas  75.0       NaN
3      new york  68.0      68.0
4       orlando   NaN      75.0
5  san fransico   NaN      45.0