In [1]:
import pandas as pd

In [5]:
df = pd.read_csv("C:\\Users\\Chandra Mouli\\Desktop\\Ai_Eng\\CSV_Files\\weather_by_cities.csv")
df

         day      city  temperature  windspeed   event
0   1/1/2017  new york           32          6    Rain
1   1/2/2017  new york           36          7   Sunny
2   1/3/2017  new york           28         12    Snow
3   1/4/2017  new york           33          7   Sunny
4   1/1/2017    mumbai           90          5   Sunny
5   1/2/2017    mumbai           85         12     Fog
6   1/3/2017    mumbai           87         15     Fog
7   1/4/2017    mumbai           92          5    Rain
8   1/1/2017     paris           45         20   Sunny
9   1/2/2017     paris           50         13  Cloudy
10  1/3/2017     paris           54          8  Cloudy
11  1/4/2017     paris           42         10  Cloudy

In [7]:
df[df.city == 'new york'].temperature.max()

np.int64(36)

In [8]:
g = df.groupby("city")
g

In [12]:
for city,data in g:
    print("city : ",city)
    print("\n")
    print("data :",data)

city :  mumbai


data :         day    city  temperature  windspeed  event
4  1/1/2017  mumbai           90          5  Sunny
5  1/2/2017  mumbai           85         12    Fog
6  1/3/2017  mumbai           87         15    Fog
7  1/4/2017  mumbai           92          5   Rain
city :  new york


data :         day      city  temperature  windspeed  event
0  1/1/2017  new york           32          6   Rain
1  1/2/2017  new york           36          7  Sunny
2  1/3/2017  new york           28         12   Snow
3  1/4/2017  new york           33          7  Sunny
city :  paris


data :          day   city  temperature  windspeed   event
8   1/1/2017  paris           45         20   Sunny
9   1/2/2017  paris           50         13  Cloudy
10  1/3/2017  paris           54          8  Cloudy
11  1/4/2017  paris           42         10  Cloudy

In [15]:
for city,data in g:
    print("city : ",city)
    print("Max temp :",data.temperature.max())
    print("\n")

city :  mumbai
Max temp : 92


city :  new york
Max temp : 36


city :  paris
Max temp : 54

In [16]:
g.get_group("mumbai")

        day    city  temperature  windspeed  event
4  1/1/2017  mumbai           90          5  Sunny
5  1/2/2017  mumbai           85         12    Fog
6  1/3/2017  mumbai           87         15    Fog
7  1/4/2017  mumbai           92          5   Rain

In [17]:
g.max()

               day  temperature  windspeed  event
city
mumbai    1/4/2017           92         15  Sunny
new york  1/4/2017           36         12  Sunny
paris     1/4/2017           54         20  Sunny

In [18]:
g.min()

               day  temperature  windspeed   event
city
mumbai    1/1/2017           85          5     Fog
new york  1/1/2017           28          6    Rain
paris     1/1/2017           42          8  Cloudy

In [21]:
#df --> split --> apply ---> combine

In [22]:
g.describe()

         temperature                                                   \
               count   mean       std   min    25%   50%    75%   max
city
mumbai           4.0  88.50  3.109126  85.0  86.50  88.5  90.50  92.0
new york         4.0  32.25  3.304038  28.0  31.00  32.5  33.75  36.0
paris            4.0  47.75  5.315073  42.0  44.25  47.5  51.00  54.0

         windspeed
             count   mean       std  min   25%   50%    75%   max
city
mumbai         4.0   9.25  5.057997  5.0  5.00   8.5  12.75  15.0
new york       4.0   8.00  2.708013  6.0  6.75   7.0   8.25  12.0
paris          4.0  12.75  5.251984  8.0  9.50  11.5  14.75  20.0

In [23]:
g.size()

city
mumbai      4
new york    4
paris       4
dtype: int64

In [29]:
def grouper(df,idx,col):
     if 80 <= df[col].loc[idx] <=90:
        return '80-90'
     elif 50 <= df[col].loc[idx]<=60:
        return '50-60'
     else:
        return 'others'

In [30]:
g = df.groupby(lambda idx : grouper(df,idx,"temperature"))
g

In [31]:
g.describe()

       temperature                                                      \
             count       mean        std   min   25%   50%   75%   max
50-60          2.0  52.000000   2.828427  50.0  51.0  52.0  53.0  54.0
80-90          3.0  87.333333   2.516611  85.0  86.0  87.0  88.5  90.0
others         7.0  44.000000  21.962089  28.0  32.5  36.0  43.5  92.0

       windspeed
           count       mean       std  min   25%   50%    75%   max
50-60        2.0  10.500000  3.535534  8.0  9.25  10.5  11.75  13.0
80-90        3.0  10.666667  5.131601  5.0  8.50  12.0  13.50  15.0
others       7.0   9.571429  5.191568  5.0  6.50   7.0  11.00  20.0

In [32]:
for key,d in g:
    print("Key : ",key)
    print("\n")
    print("Data :",d)

Key :  50-60


Data :          day   city  temperature  windspeed   event
9   1/2/2017  paris           50         13  Cloudy
10  1/3/2017  paris           54          8  Cloudy
Key :  80-90


Data :         day    city  temperature  windspeed  event
4  1/1/2017  mumbai           90          5  Sunny
5  1/2/2017  mumbai           85         12    Fog
6  1/3/2017  mumbai           87         15    Fog
Key :  others


Data :          day      city  temperature  windspeed   event
0   1/1/2017  new york           32          6    Rain
1   1/2/2017  new york           36          7   Sunny
2   1/3/2017  new york           28         12    Snow
3   1/4/2017  new york           33          7   Sunny
7   1/4/2017    mumbai           92          5    Rain
8   1/1/2017     paris           45         20   Sunny
11  1/4/2017     paris           42         10  Cloudy