In [1]:
import pandas as pd

In [19]:
df = pd.read_csv("C:\\Users\\Chandra Mouli\\Desktop\\Ai_Eng\\weather_data.csv")
df

        day  temperature  windspeed     event
0  1/1/2017           32          6      Rain
1  1/2/2017       -99999          7     Sunny
2  1/3/2017           28     -99999      Snow
3  1/4/2017       -99999          7  no event
4  1/5/2017           32     -99999      Rain
5  1/6/2017           31          2     Sunny
6  1/6/2017           34     -88888  no event

In [7]:
#df.replace(-99999,0)
import numpy as np
df.replace(-99999,np.nan)

        day  temperature  windspeed     event
0  1/1/2017         32.0        6.0      Rain
1  1/2/2017          NaN        7.0     Sunny
2  1/3/2017         28.0        NaN      Snow
3  1/4/2017          NaN        7.0  no event
4  1/5/2017         32.0        NaN      Rain
5  1/6/2017         31.0        2.0     Sunny
6  1/6/2017         34.0   -88888.0  no event

In [11]:
df.replace(to_replace=[-99999,-88888],value = np.nan)
#df.replace([-99999,-88888],np.nan)

        day  temperature  windspeed     event
0  1/1/2017         32.0        6.0      Rain
1  1/2/2017          NaN        7.0     Sunny
2  1/3/2017         28.0        NaN      Snow
3  1/4/2017          NaN        7.0  no event
4  1/5/2017         32.0        NaN      Rain
5  1/6/2017         31.0        2.0     Sunny
6  1/6/2017         34.0        NaN  no event

In [16]:
df

        day  temperature  windspeed     event
0  1/1/2017           32          6      Rain
1  1/2/2017       -99999          7     Sunny
2  1/3/2017           28     -99999      Snow
3  1/4/2017       -99999          7  no event
4  1/5/2017           32     -99999      Rain
5  1/6/2017           31          2     Sunny
6  1/6/2017           34     -88888  no event

In [14]:
df.replace({
 'temperature':-99999,
  'windspeed':[-88888,-99999],
  'event':'no event'},np.nan)

        day  temperature  windspeed  event
0  1/1/2017         32.0        6.0   Rain
1  1/2/2017          NaN        7.0  Sunny
2  1/3/2017         28.0        NaN   Snow
3  1/4/2017          NaN        7.0    NaN
4  1/5/2017         32.0        NaN   Rain
5  1/6/2017         31.0        2.0  Sunny
6  1/6/2017         34.0        NaN    NaN

In [20]:
df.replace({
-99999:np.nan,
-88888:np.nan,
'no event':'sunny'
})

        day  temperature  windspeed  event
0  1/1/2017         32.0        6.0   Rain
1  1/2/2017          NaN        7.0  Sunny
2  1/3/2017         28.0        NaN   Snow
3  1/4/2017          NaN        7.0  sunny
4  1/5/2017         32.0        NaN   Rain
5  1/6/2017         31.0        2.0  Sunny
6  1/6/2017         34.0        NaN  sunny

In [22]:
df = pd.DataFrame({
'score':['exceptional','average','good','poor','average','exceptional'],
'student':['rob','maya','parthiv','tom','julian','erica']
})
df

         score  student
0  exceptional      rob
1      average     maya
2         good  parthiv
3         poor      tom
4      average   julian
5  exceptional    erica

In [23]:
df.replace(['poor','average','good','exceptional'],[1,2,3,4])

  score  student
0     4      rob
1     2     maya
2     3  parthiv
3     1      tom
4     2   julian
5     4    erica