In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("C:\\Users\\Chandra Mouli\\Desktop\\Ai_Eng\\CSV_Files\\stock_data.csv")
df

,Datasource: Google finance,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,tickers,eps,revenue,price,people
1,GOOGL,27.82,87,845,larry page
2,WMT,4.61,484,65,n.a.
3,MSFT,-1,85,64,bill gates
4,RIL,not available,50,1023,mukesh ambani
5,TATA,5.6,-1,n.a.,ratan tata

In [4]:
#DataSource is Header use skiprows to hide go doc for another funcs/explanation
df = pd.read_csv("C:\\Users\\Chandra Mouli\\Desktop\\Ai_Eng\\CSV_Files\\stock_data.csv",skiprows=1)
df

  tickers            eps  revenue price         people
0   GOOGL          27.82       87   845     larry page
1     WMT           4.61      484    65           n.a.
2    MSFT             -1       85    64     bill gates
3    RIL   not available       50  1023  mukesh ambani
4    TATA            5.6       -1  n.a.     ratan tata

In [5]:
df = pd.read_csv("C:\\Users\\Chandra Mouli\\Desktop\\Ai_Eng\\CSV_Files\\stock_data.csv",header = 1)
df

  tickers            eps  revenue price         people
0   GOOGL          27.82       87   845     larry page
1     WMT           4.61      484    65           n.a.
2    MSFT             -1       85    64     bill gates
3    RIL   not available       50  1023  mukesh ambani
4    TATA            5.6       -1  n.a.     ratan tata

In [8]:
df = pd.read_csv("C:\\Users\\Chandra Mouli\\Desktop\\Ai_Eng\\CSV_Files\\stock_data.csv",header = 1,names = ["Stock Symbol","eps","revenue","price","people"])
df # Changing column names

  Stock Symbol            eps  revenue price         people
0        GOOGL          27.82       87   845     larry page
1          WMT           4.61      484    65           n.a.
2         MSFT             -1       85    64     bill gates
3         RIL   not available       50  1023  mukesh ambani
4         TATA            5.6       -1  n.a.     ratan tata

In [10]:
df = pd.read_csv("C:\\Users\\Chandra Mouli\\Desktop\\Ai_Eng\\CSV_Files\\stock_data.csv",header = 1,nrows = 2)
df # Reading only nrows if u have million records

  tickers    eps  revenue  price      people
0   GOOGL  27.82       87    845  larry page
1     WMT   4.61      484     65        n.a.

In [20]:
df = pd.read_csv("C:\\Users\\Chandra Mouli\\Desktop\\Ai_Eng\\CSV_Files\\stock_data.csv",header = 1,na_values = { 
          'eps':['not available'],
          'revenue':[-1],
           'people' : ['not available','n.a.'],
           'price' : ['n.a.']
})
df # Converting not available to NaN using obj

  tickers    eps  revenue   price         people
0   GOOGL  27.82     87.0   845.0     larry page
1     WMT   4.61    484.0    65.0            NaN
2    MSFT  -1.00     85.0    64.0     bill gates
3    RIL     NaN     50.0  1023.0  mukesh ambani
4    TATA   5.60      NaN     NaN     ratan tata

In [82]:
df = pd.read_csv("C:\\Users\\Chandra Mouli\\Desktop\\Ai_Eng\\CSV_Files\\stock_data.csv",header = 1,na_values = ['not available','n.a.',-1])
df # converting na values using list

  tickers    eps  revenue   price         people
0   GOOGL  27.82     87.0   845.0     larry page
1     WMT   4.61    484.0    65.0            NaN
2    MSFT    NaN     85.0    64.0     bill gates
3    RIL     NaN     50.0  1023.0  mukesh ambani
4    TATA   5.60      NaN     NaN     ratan tata

In [83]:
df["pe"] = df["price"]/df["eps"]
df

  tickers    eps  revenue   price         people         pe
0   GOOGL  27.82     87.0   845.0     larry page  30.373832
1     WMT   4.61    484.0    65.0            NaN  14.099783
2    MSFT    NaN     85.0    64.0     bill gates        NaN
3    RIL     NaN     50.0  1023.0  mukesh ambani        NaN
4    TATA   5.60      NaN     NaN     ratan tata        NaN

In [84]:
df.to_csv("pe.csv")

In [85]:
df = pd.read_csv("C:\\Users\\Chandra Mouli\\PycharmProjects1\\Rough\\Pandas\\pe.csv")
df

   Unnamed: 0 tickers    eps  revenue   price         people         pe
0           0   GOOGL  27.82     87.0   845.0     larry page  30.373832
1           1     WMT   4.61    484.0    65.0            NaN  14.099783
2           2    MSFT    NaN     85.0    64.0     bill gates        NaN
3           3    RIL     NaN     50.0  1023.0  mukesh ambani        NaN
4           4    TATA   5.60      NaN     NaN     ratan tata        NaN

In [86]:
df.columns

Index(['Unnamed: 0', 'tickers', 'eps', 'revenue', 'price', 'people', 'pe'], dtype='str')

In [87]:
df = df.loc[:, ~df.columns.str.contains('^Unnamed')]

In [88]:
df.to_csv("pe1.csv",index=False,header=False)

In [89]:
df = pd.read_csv("pe1.csv",header=0)
#df = df.drop(columns=df.columns[df.columns.str.contains('^Unnamed')])
df

  GOOGL  27.82   87.0   845.0     larry page  30.373831775700936
0   WMT   4.61  484.0    65.0            NaN           14.099783
1  MSFT    NaN   85.0    64.0     bill gates                 NaN
2  RIL     NaN   50.0  1023.0  mukesh ambani                 NaN
3  TATA   5.60    NaN     NaN     ratan tata                 NaN