In [1]:
import pandas as pd

In [123]:
df = pd.read_csv("C:\\Users\\Chandra Mouli\\Desktop\\Ai_Eng\\CSV_Files\\stock_data.csv")
df

,Datasource: Google finance,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,tickers,eps,revenue,price,people
1,GOOGL,27.82,87,845,larry page
2,WMT,4.61,484,65,n.a.
3,MSFT,-1,85,64,bill gates
4,RIL,not available,50,1023,mukesh ambani
5,TATA,5.6,-1,n.a.,ratan tata

In [124]:
#DataSource is Header use skiprows to hide go doc for another funcs/explanation
df = pd.read_csv("C:\\Users\\Chandra Mouli\\Desktop\\Ai_Eng\\CSV_Files\\stock_data.csv",skiprows=1)
df

  tickers            eps  revenue price         people
0   GOOGL          27.82       87   845     larry page
1     WMT           4.61      484    65           n.a.
2    MSFT             -1       85    64     bill gates
3    RIL   not available       50  1023  mukesh ambani
4    TATA            5.6       -1  n.a.     ratan tata

In [125]:
df = pd.read_csv("C:\\Users\\Chandra Mouli\\Desktop\\Ai_Eng\\CSV_Files\\stock_data.csv",header = 1)
df

  tickers            eps  revenue price         people
0   GOOGL          27.82       87   845     larry page
1     WMT           4.61      484    65           n.a.
2    MSFT             -1       85    64     bill gates
3    RIL   not available       50  1023  mukesh ambani
4    TATA            5.6       -1  n.a.     ratan tata

In [126]:
df = pd.read_csv("C:\\Users\\Chandra Mouli\\Desktop\\Ai_Eng\\CSV_Files\\stock_data.csv",header = 1,names = ["Stock Symbol","eps","revenue","price","people"])
df # Changing column names

  Stock Symbol            eps  revenue price         people
0        GOOGL          27.82       87   845     larry page
1          WMT           4.61      484    65           n.a.
2         MSFT             -1       85    64     bill gates
3         RIL   not available       50  1023  mukesh ambani
4         TATA            5.6       -1  n.a.     ratan tata

In [127]:
df = pd.read_csv("C:\\Users\\Chandra Mouli\\Desktop\\Ai_Eng\\CSV_Files\\stock_data.csv",header = 1,nrows = 2)
df # Reading only nrows if u have million records

  tickers    eps  revenue  price      people
0   GOOGL  27.82       87    845  larry page
1     WMT   4.61      484     65        n.a.

In [128]:
df = pd.read_csv("C:\\Users\\Chandra Mouli\\Desktop\\Ai_Eng\\CSV_Files\\stock_data.csv",header = 1,na_values = { 
          'eps':['not available'],
          'revenue':[-1],
           'people' : ['not available','n.a.'],
           'price' : ['n.a.']
})
df # Converting not available to NaN using obj

  tickers    eps  revenue   price         people
0   GOOGL  27.82     87.0   845.0     larry page
1     WMT   4.61    484.0    65.0            NaN
2    MSFT  -1.00     85.0    64.0     bill gates
3    RIL     NaN     50.0  1023.0  mukesh ambani
4    TATA   5.60      NaN     NaN     ratan tata

In [139]:
df = pd.read_csv("C:\\Users\\Chandra Mouli\\Desktop\\Ai_Eng\\CSV_Files\\stock_data.csv",header = 1,na_values = ['not available','n.a.',-1])
df # converting na values using list

  tickers    eps  revenue   price         people
0   GOOGL  27.82     87.0   845.0     larry page
1     WMT   4.61    484.0    65.0            NaN
2    MSFT    NaN     85.0    64.0     bill gates
3    RIL     NaN     50.0  1023.0  mukesh ambani
4    TATA   5.60      NaN     NaN     ratan tata

In [141]:
df["pe"] = df["price"]/df["eps"]
df

  tickers    eps  revenue   price         people         pe
0   GOOGL  27.82     87.0   845.0     larry page  30.373832
1     WMT   4.61    484.0    65.0            NaN  14.099783
2    MSFT    NaN     85.0    64.0     bill gates        NaN
3    RIL     NaN     50.0  1023.0  mukesh ambani        NaN
4    TATA   5.60      NaN     NaN     ratan tata        NaN

In [142]:
df.to_csv("pe.csv")

In [144]:
df = pd.read_csv("pe.csv")
df

   Unnamed: 0 tickers    eps  revenue   price         people         pe
0           0   GOOGL  27.82     87.0   845.0     larry page  30.373832
1           1     WMT   4.61    484.0    65.0            NaN  14.099783
2           2    MSFT    NaN     85.0    64.0     bill gates        NaN
3           3    RIL     NaN     50.0  1023.0  mukesh ambani        NaN
4           4    TATA   5.60      NaN     NaN     ratan tata        NaN

In [145]:
df.columns

Index(['Unnamed: 0', 'tickers', 'eps', 'revenue', 'price', 'people', 'pe'], dtype='str')

In [146]:
df

   Unnamed: 0 tickers    eps  revenue   price         people         pe
0           0   GOOGL  27.82     87.0   845.0     larry page  30.373832
1           1     WMT   4.61    484.0    65.0            NaN  14.099783
2           2    MSFT    NaN     85.0    64.0     bill gates        NaN
3           3    RIL     NaN     50.0  1023.0  mukesh ambani        NaN
4           4    TATA   5.60      NaN     NaN     ratan tata        NaN

In [147]:
df = df.loc[:, ~df.columns.str.contains('^Unnamed')]

In [158]:
df

  tickers    eps  revenue   price         people         pe
0   GOOGL  27.82     87.0   845.0     larry page  30.373832
1     WMT   4.61    484.0    65.0            NaN  14.099783
2    MSFT    NaN     85.0    64.0     bill gates        NaN
3    RIL     NaN     50.0  1023.0  mukesh ambani        NaN
4    TATA   5.60      NaN     NaN     ratan tata        NaN

In [160]:
df.to_csv("pe1.csv",index=False,header=False) # saved correctly but while reading it is giving index and header as first row

In [162]:
df = pd.read_csv("pe1.csv", header=None)
df.columns = ["tickers","eps","revenue","price","people","pe"]
df # Need to work on it later not in v

  tickers    eps  revenue   price         people         pe
0   GOOGL  27.82     87.0   845.0     larry page  30.373832
1     WMT   4.61    484.0    65.0            NaN  14.099783
2    MSFT    NaN     85.0    64.0     bill gates        NaN
3    RIL     NaN     50.0  1023.0  mukesh ambani        NaN
4    TATA   5.60      NaN     NaN     ratan tata        NaN

In [166]:
pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [179]:
#Excel Files
df_movies = pd.read_excel("C:\\Users\\Chandra Mouli\\Desktop\\Ai_Eng\\CSV_Files\\movies_db.xlsx","movies")
df_movies.head(4)

,movie_id,title,industry,release_year,imdb_rating,studio,language_id
0,101,K.G.F: Chapter 2,Bollywood,2022,8.4,Hombale Films,3
1,102,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,5
2,103,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,5
3,104,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,5

In [180]:
df_finicials = pd.read_excel("C:\\Users\\Chandra Mouli\\Desktop\\Ai_Eng\\CSV_Files\\movies_db.xlsx","financials")
df_finicials.head(4)

   movie_id  budget  revenue      unit currency
0       101     1.0     12.5  Billions      INR
1       102   200.0    954.8  Millions      USD
2       103   165.0    644.8  Millions       $$
3       104   180.0    854.0  Millions  Dollars

In [181]:
def standardize_currency(curr):
     if curr == "$$" or curr == "Dollars":
         return "USD"
     return curr
df_finicials = pd.read_excel("C:\\Users\\Chandra Mouli\\Desktop\\Ai_Eng\\CSV_Files\\movies_db.xlsx","financials",converters = {
  'currency':standardize_currency 

})
df_finicials.head(5) #use google to get ideas about conversions

   movie_id  budget  revenue      unit currency
0       101     1.0     12.5  Billions      INR
1       102   200.0    954.8  Millions      USD
2       103   165.0    644.8  Millions      USD
3       104   180.0    854.0  Millions      USD
4       105   250.0    670.0  Millions      USD

In [182]:
df_merged = pd.merge(df_movies,df_finicials,on = "movie_id")
df_merged.head(4)

,movie_id,title,industry,release_year,imdb_rating,studio,language_id,budget,revenue,unit,currency
0,101,K.G.F: Chapter 2,Bollywood,2022,8.4,Hombale Films,3,1.0,12.5,Billions,INR
1,102,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,5,200.0,954.8,Millions,USD
2,103,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,5,165.0,644.8,Millions,USD
3,104,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,5,180.0,854.0,Millions,USD

In [183]:
df_merged.to_excel("Movies_merged.xlsx",sheet_name = "Sheet1",index = False)

In [185]:
df_stocks = pd.DataFrame({
  'tickers' : ['GOOGL','WMT','MSFT'],
  'price' : [845,65,64],
   'pe' : [30.37,14.26,30.97],
   'eps' : [27.82,4.61,2.12]
})
df_stocks

  tickers  price     pe    eps
0   GOOGL    845  30.37  27.82
1     WMT     65  14.26   4.61
2    MSFT     64  30.97   2.12

In [186]:
df_weather = pd.DataFrame({
  'day' : ['1/4/2026','1/2/2026','1/3/2026'],
  'temparature' : [32,35,28],
  'event' : ['Rain','Sunny','Snow']
})
df_weather

        day  temparature  event
0  1/4/2026           32   Rain
1  1/2/2026           35  Sunny
2  1/3/2026           28   Snow

In [187]:
with pd.ExcelWriter("stocks_Weather.xlsx") as writer:
      df_stocks.to_excel(writer,sheet_name = "stocks")
      df_weather.to_excel(writer,sheet_name = "weather")